version: '3'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: nest
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge
